[package]
name = "rebicycler"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-sc2 = { git = "https://github.com/UltraMachine/rust-sc2" }
slotmap = "1.0.7"
console = "0.15.11"
itertools = "0.14.0"
image = "0.25.6"
ego-tree="0.10.0"